###############################################################
#
# Purpose: Makefile for "M-JPEG Streamer"
# Author.: Tom Stoeveken (TST)
# Version: 0.3
# License: GPL
#
###############################################################

obj-y += input_uvc.o
obj-y += v4l2uvc.o
obj-y += jpeg_utils.o
obj-y += dynctrl.o


